steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'backend'
  args: [ 'build', '-t', '$_REGION_-docker.pkg.dev/$_PROJECT_ID_/backend/backend', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '$_REGION_-docker.pkg.dev/$_PROJECT_ID_/backend/backend']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'backend', '--image', '$_REGION_-docker.pkg.dev/$_PROJECT_ID_/backend/backend', '--region', '$_REGION_']
options:
  logging: CLOUD_LOGGING_ONLY
images:
- $_REGION_-docker.pkg.dev/$_PROJECT_ID_/backend/backend